from typing import Callable

_apply_ui_emojis_fn: Callable[[str], str] | None = None


def _apply_ui_emojis(text: str) -> str:
    """Apply configured UI emoji overrides without triggering circular imports."""

    global _apply_ui_emojis_fn

    if _apply_ui_emojis_fn is None:
        from bot.utils.emoji import apply_ui_emojis as _apply

        _apply_ui_emojis_fn = _apply

    return _apply_ui_emojis_fn(text)


LANGUAGES = {
    'en': {
        'hello': '👋 Hello, {user}!',
        'balance': '💰 Balance: {balance} EUR',
        'overpay': '💳 Send the exact amount. Overpayments will be credited.',
        'shop': '🛍 Shop',
        'profile': '👤 Profile',
        'top_up': '💸 Top Up',
        'channel': '📢 Channel',
        'price_list': '💲 Price List',
        'language': '🌐 Language',
        'admin_panel': '🎛 Admin Panel',
        'help': '❓ Help',
        'help_info': (
            'Use the main menu to work with the bot:\n'
            '🛍 Shop – browse categories and choose a product.\n'
            '   • Select an item and confirm to purchase it.\n'
            '👤 Profile – view your balance and purchased items.\n'
            '💸 Top Up – choose a payment method and follow the instructions to add funds.\n'
            '🌐 Language – switch the interface language.\n'
            '🎁 Purchased items – available in Profile after you buy something.\n'
            'If you need assistance, contact {helper}.'
        ),
        'admin_help_info': (
            'Admin panel functions:\n'
            '🛠 Assign assistants – manage assistant accounts.\n'
            '👔 Assign owners – grant owner privileges to another account.\n'
            '📦 View Stock – browse and delete available product stock.\n'
            '🏪 Parduotuvės valdymas – manage shop categories and items.\n'
            '👥 Vartotojų valdymas – manage user balances and roles.\n'
            '📢 Pranešimų siuntimas – send messages to all users.'
        ),
        'assistant_help_info': (
            'Assistant panel functions:\n'
            '🖼 Assign photos – attach photos to items.\n'
            'Use Back to menu to return.'
        ),
        'choose_language': 'Please choose a language',
        'invoice_message': (
            '🧾 <b>Payment Invoice Created</b>\n\n'
            '<b>Amount:</b> <code>{amount}</code> {currency}\n'
            '🏦 <b>Payment Address:</b>\n<code>{address}</code>\n\n'
            '⏳ <b>Expires At:</b> {expires_at} LT\n'
            '⚠️ <b>Payment must be completed within 15 minutes of invoice creation.</b>\n\n'
            '❗️ <b>Important:</b> Send <u>exactly</u> this amount of {currency}.\n\n'
            '✅ <b>Confirmation is automatic via webhook after network confirmation.</b>'
        ),
        'cancel': 'Cancel',
        'cancel_payment': '❌ Cancel Payment',
        'payment_successful': '✅ Payment confirmed. Balance increased by {amount}€',
        'back_home': 'Back Home',
        'invoice_cancelled': 'Payment failed/expired. Your items are no longer reserved.',
        'total_purchases': '📦 Total Purchases: {count}',
        'streak': '🔥 Streak: {days} days',
        'note': '⚠️ Note: No refunds. Please ensure you send the exact amount for payments, as underpayments will not be confirmed.',
        'rate_limited': '⏳ Too many requests. Please slow down.',
        'captcha_prompt': 'Please solve the equation shown in the image.',
        'captcha_prompt_fallback': 'Please solve this equation: {expression} = ?',
        'captcha_failed': '❌ Incorrect answer. Try again.',
        'captcha_success': '✅ Captcha solved! Continuing...',
        'rate_experience': '⭐ How was your overall experience?',
        'rate_service': 'How was your experience with the service?',
        'rate_product': 'What is your opinion on the product?',
        'ask_feedback_reason': 'Would you like to tell us why?',
        'feedback_reason': 'Please write your feedback:',
        'thanks_feedback': 'Thanks for your feedback!',
        'confirm_purchase': 'Confirm purchase of {item} for {price}€?',
        'purchase_button': 'Purchase',
        'buy_now': '💰 Buy now',
        'add_to_cart': '🛒 Add to cart',
        'apply_promo': 'Apply promo code',
        'promo_prompt': 'Send promo code:',
        'promo_invalid': '❌ Invalid or expired promo code',
        'promo_applied': '✅ Promo code applied. New price: {price}€',
        'promo_not_applicable': '❌ This promo code cannot be used for this product.',
        'yes': '✅ Yes',
        'no': '❌ No',
        'confirm': '✅ Confirm',
        'rerun': '🔄 Rerun',
        'assign_more': '✅ Photo assigned. Add another?',
        'assign_no_categories': '❌ No categories available for media assignment.',
        'assign_choose_main': '🖼 Media assignment\nSelect a main category:',
        'assign_choose_category': '🖼 Media assignment\nChoose a category or product:\nPath: {path}',
        'assign_empty_branch_button': '⚠️ Empty branch',
        'assign_empty_branch': 'This branch does not contain categories or products.',
        'assign_media_prompt': 'Send a photo or video for <b>{item}</b> (DROPAI):',
        'assign_current_path': 'Path: <code>{path}</code>',
        'assign_media_invalid': '❌ Please send a photo or a video.',
        'assign_desc_prompt': 'Write a description for this media (KOORDINATES):',
        'purchased_items': '📦 Purchased items',
        'purchased_items': '🎁 Purchased items',
        'back_to_menu': '🔙 Back to menu',
        'users_tickets': '🎟️ User tickets:',
        'no_tickets': 'No tickets',
        'lottery_winner': '🎉 Winner: {username}\n🎟️ Tickets: {tickets}\n\n❗️ Confirming will reset all tickets.',
        'lottery_broadcast_prompt': 'Send message to all users?',
        'lottery_enter_message': '✉️ Enter message:',
        'lottery_finished': '✅ Lottery finished.',
        'no_winner': '❌ No winner',
        'tools': '🧰 Tools',
        'lottery': '🎟️ Lottery',
        'insufficient_rights': 'Insufficient rights',
        'passwords_menu_title': '🔐 Password management',
        'passwords_generate_prompt': 'How many passwords should be generated?',
        'passwords_generate_invalid': 'Please enter a valid number.',
        'passwords_generate_limit': 'Enter a number between 1 and 100.',
        'passwords_generated': 'Generated {count} password(s):',
        'passwords_no_categories': 'No main categories available.',
        'passwords_lock_title': '🔒 Lock main categories',
        'passwords_lock_applied': 'Category "{category}" locked.',
        'passwords_lock_removed': 'Category "{category}" unlocked.',
        'passwords_view_users_title': '👥 Users with passwords',
        'passwords_no_user_entries': 'No users have used a password yet.',
        'passwords_user_overview': 'User {user}',
        'passwords_user_entry': '{category}: <code>{password}</code> ({status}) — {updated}',
        'passwords_user_entry_changed': 'custom',
        'passwords_user_entry_generated': 'generated',
        'passwords_user_deleted': 'Password removed.',
        'passwords_admin_change_prompt': 'Send a new password for {user} in {category}:',
        'passwords_admin_change_done': 'Updated password for {user} in {category}.',
        'passwords_change_empty': 'Password cannot be empty.',
        'passwords_change_too_long': 'Password must be 64 characters or fewer.',
        'passwords_locked': 'Category "{category}" is locked.',
        'passwords_prompt': 'Enter the password for {category}:',
        'passwords_invalid': 'Incorrect password. Try again.',
        'passwords_valid': 'Password accepted for {category}.',
        'passwords_change_prompt': 'Send a new password for {category}:',
        'passwords_change_done': 'Password updated for {category}. New password:\n<code>{password}</code>',
        'passwords_keep': 'Keep password',
        'passwords_change': 'Change password',
        'passwords_continue': '➡️ Continue',
        'use_balance_prompt': 'You have {balance}€. Use it to reduce the price?',
        'choose_crypto': 'Choose payment method:',
        'need_top_up': 'You need to top up {missing}€ to complete the purchase. Choose payment method:',
        'item_reserved': '🔒 Item reserved for you for 15 minutes.',
        'payment_cancelled': '✅ Payment cancelled. Reserved items have been released.',
        'top_up_completed': '✅ Top-up completed.',
        'lottery_ticket_awarded': '🎟️ You received a lottery ticket.',
        'lottery_tickets': '🎟️ <b>Lottery tickets</b> - <code>{tickets}</code>',
        'referral_link': '🤝 <b>Referral link</b> - <code>{link}</code>',
        'referrals': '👥 <b>Referrals</b> - {count}',
        'referral_earnings': '💰 <b>Referral earnings</b> - <code>{amount}</code> €',
        'referral_reward': '🎉 Your referral {user} purchased a product - you earned {amount}€!',
        'gift': '🎀 Gift to',
        'gift_prompt': 'Who do you want to gift a product to?',
        'gift_user_not_found': '❌ User not found.',
        'gift_select_category': '🎀 Select a product to gift to {user}:',
        'gift_sent': '🎀 Gift sent to {user}!',
        'gift_received': '🎀 You received {item} from {user}!',
        'catalog_editor_menu_title': '🛠️ Catalog editor menu',
        'catalog_editor_button_main': '✏️ Edit main category',
        'catalog_editor_button_category': '✏️ Edit category/subcategory',
        'catalog_editor_button_item': '✏️ Edit product',
        'catalog_buttons_overview': '🔘 Button layout editor\n\nCurrent layout:\n{layout}\n\nSelect a button to adjust or reset to defaults.',
        'catalog_buttons_preview_empty': 'No buttons configured yet.',
        'catalog_buttons_status_active': 'Active',
        'catalog_buttons_status_hidden': 'Hidden',
        'catalog_buttons_action_reset': '♻️ Reset to defaults',
        'catalog_buttons_action_text': '🔤 Rename button',
        'catalog_buttons_action_position': '📐 Change position',
        'catalog_buttons_action_toggle_off': '🚫 Hide button',
        'catalog_buttons_action_toggle_on': '✅ Show button',
        'catalog_buttons_action_link': '🔗 Update channel link',
        'catalog_buttons_button_info': 'Button: {name}\nRow: {row}\nColumn: {column}\nStatus: {status}',
        'catalog_buttons_button_actions': 'Choose an action below to update this button.',
        'catalog_buttons_column_left': 'Left',
        'catalog_buttons_column_right': 'Right',
        'catalog_buttons_position_label': 'Row {row} • {column}',
        'catalog_buttons_position_new_suffix': '(new row)',
        'catalog_buttons_position_title': 'Select a new position for {name}:',
        'catalog_buttons_prompt_text': 'Send a new label for {name}:',
        'catalog_buttons_prompt_link': 'Send a new link for {name} (use \'-\' to clear and fallback to default):',
        'catalog_buttons_toggle_enabled': 'Button is now visible.',
        'catalog_buttons_toggle_disabled': 'Button is now hidden.',
        'catalog_buttons_invalid_position': 'Invalid position selected.',
        'catalog_buttons_position_same': 'This button is already in that slot.',
        'catalog_buttons_position_updated': 'Button position updated.',
        'catalog_buttons_reset_prompt': 'Reset the button layout to the default configuration?',
        'catalog_buttons_reset_done': 'Layout restored to defaults.',
        'catalog_buttons_invalid_text': 'Label cannot be empty.',
        'catalog_buttons_text_too_long': 'Label must be at most 64 characters.',
        'catalog_buttons_text_updated': 'Button label updated.',
        'catalog_buttons_link_updated': 'Channel link updated.',
        'catalog_buttons_link_cleared': 'Channel link cleared. The default link will be used.',
        'catalog_buttons_invalid_link': 'Provide a valid URL or \'-\' to clear the link.',
        'catalog_no_main_categories': '❌ No main categories available. Create one first.',
        'catalog_no_categories_available': '❌ No categories available. Create a main category first.',
        'state_enabled': '✅ Enabled',
        'state_disabled': '❌ Disabled',
        'catalog_select_category_first': 'Select a category first',
        'catalog_text_intro': 'Select the language to edit the main menu message.',
        'catalog_text_language_en': '🇬🇧 English',
        'catalog_text_language_ru': '🇷🇺 Russian',
        'catalog_text_language_lt': '🇱🇹 Lithuanian',
        'catalog_text_preview_title': '{language} main menu message:',
        'catalog_text_placeholders': 'Available placeholders:\n{placeholders}',
        'catalog_text_action_edit': '✏️ Update text',
        'catalog_text_action_reset': '♻️ Reset to default',
        'catalog_text_prompt': (
            'Send a new main menu message for <b>{language}</b>.\n\n'
            'Placeholders:\n{placeholders}'
        ),
        'catalog_text_placeholder_user': 'user mention with a profile link',
        'catalog_text_placeholder_balance': 'numeric balance value (e.g. 0.00)',
        'catalog_text_placeholder_currency': 'currency code (e.g. EUR)',
        'catalog_text_placeholder_purchases': 'total number of completed purchases',
        'catalog_text_placeholder_status': 'loyalty status with emoji',
        'catalog_text_placeholder_streak_line': 'preformatted streak line with emoji',
        'catalog_text_placeholder_streak_days': 'number of days in the current streak',
        'catalog_text_placeholder_note': 'default note about payment accuracy',
        'catalog_emojis_title': '✨ Emoji editor',
        'catalog_emojis_help': 'Configure emoji replacements shown to customers. Overrides apply instantly.',
        'catalog_emojis_empty': 'No emoji overrides are active.',
        'catalog_emojis_list_intro': 'Current overrides:',
        'catalog_emojis_override_line': '{original} → {replacement}',
        'catalog_emojis_add_override': '➕ Add or update override',
        'catalog_emojis_reset_all': '♻️ Clear all overrides',
        'catalog_emojis_prompt_original': 'Send the emoji you want to replace.',
        'catalog_emojis_prompt_replacement': (
            'Send the new emoji for {original}. Type <code>default</code> to remove the override.'
        ),
        'catalog_emojis_invalid_emoji': 'Please send a single emoji or type <code>default</code>.',
        'catalog_emojis_updated': 'Emoji updated: {original} → {replacement}',
        'catalog_emojis_removed': 'Override removed for {original}.',
        'catalog_emojis_reset': 'All emoji overrides have been cleared.',
        'catalog_emojis_remove_button': '🗑 {original} → {replacement}',
        'catalog_text_saved': '✅ Main menu text updated.',
        'catalog_text_reset_done': '✅ Main menu text restored to default.',
        'catalog_text_empty': '⚠️ Text cannot be empty.',
        'catalog_name_empty': '⚠️ Name cannot be empty',
        'catalog_name_exists': '❌ This category already exists',
        'catalog_select_main_categories': 'Select main categories for the new category:',
        'catalog_category_creation_cancelled': '❌ Category creation cancelled',
        'catalog_need_main_category': 'Select at least one main category',
        'catalog_category_name_prompt': 'Enter category name for "{parent}" ({index}/{total}):',
        'catalog_select_parents': 'Select parent categories:',
        'catalog_select_parents_path': 'Select parent categories:\nCurrent path: {path}',
        'catalog_subcategory_creation_cancelled': '❌ Subcategory creation cancelled',
        'catalog_subcategory_name_prompt': 'Enter subcategory name for "{parent}" ({index}/{total}):',
        'catalog_select_subcategories': 'Select subcategories for the product:',
        'catalog_select_subcategories_path': 'Select subcategories for the product:\nCurrent path: {path}',
        'catalog_item_name_for_destination': 'Enter product name for {path} ({index}/{total}):',
        'catalog_item_name_hint': 'Send a unique name for this location or tap below to keep "{name}".',
        'catalog_item_name_keep': 'Keep "{name}"',
        'catalog_item_name_invalid': '⚠️ Name cannot be empty.',
        'multi_select_empty': '⚠️ Empty',
        'multi_select_up': '⬆️ Up',
        'action_done': '✅ Done',
        'action_clear': '🧹 Clear',
        'action_cancel': '🔙 Cancel',
        'multi_select_no_children': 'No options in this branch.',
        'multi_select_target_missing': 'This option is no longer available.',
        'multi_select_need_category': 'Select at least one category',
        'multi_select_depth_limit': 'Maximum depth reached. Please go back.',
        'catalog_item_creation_cancelled': '❌ Item creation cancelled',
        'catalog_items_created': '✅ Items created:\n{summary}',
        'catalog_item_update_cancelled': '❌ Item update cancelled',
        'catalog_update_select_root': 'Select a category to edit a product:',
        'catalog_update_select_branch': 'Select a subcategory or product:\nCurrent path: {path}',
        'catalog_update_branch_empty_button': '⚠️ Empty branch',
        'catalog_update_branch_empty': 'This branch does not contain products.',
        'catalog_category_update_cancelled': '❌ Category update cancelled',
        'catalog_category_rename_prompt': 'Enter a new name for "{name}":',
        'catalog_category_updated': '✅ Category "{old}" renamed to "{new}".',
        'catalog_update_name_prompt': 'Enter a new name for "{name}":',
        'catalog_update_description_prompt': 'Enter a description for "{name}":',
        'catalog_update_price_prompt': 'Enter a price for "{name}":',
        'catalog_invalid_price': '⚠️ Invalid price value.',
        'catalog_item_update_complete': '✅ Item updated.',
        'catalog_update_preview_prompt': '✅ Item updated. Update preview photo for <b>{name}</b>?',
        'catalog_update_preview_send': 'Send a new preview photo for <b>{name}</b>.',
        'catalog_update_preview_saved': '✅ Preview photo updated.',
        'catalog_update_preview_cancelled': 'Preview photo left unchanged.',
        'catalog_update_preview_invalid': '❌ Please send a photo to use as the preview.',

        'stock_notify': '📦 Stock alerts',
        'choose_product_notify': 'Select a product to get notified when restocked:',
        'no_out_of_stock': '✅ All products are currently in stock.',
        'stock_subscribed': '🔔 You will be notified when {item} is back in stock.',
        'stock_already_subscribed': 'ℹ️ You are already waiting for {item}.',
        'stock_back_in': '📦 {item} is back in stock!',
        'choose_subcategory': '🏘️ Choose a city:',
        'select_product': '🏪 Select a product',
        'shop_categories': '🏪 Shop categories',
        'view_cart': '🧺 My cart',
        'cart_empty': '🧺 Your cart is empty.',
        'cart_header': '🧺 <b>My cart</b>',
        'cart_divider': '<code>────────────────────</code>',
        'cart_summary_hint': '<i>Review the items below before checkout.</i>',
        'cart_item_line': '{index}. <b>{name}</b>\n   ×<code>{quantity}</code> • <code>{unit_price}€</code> → <b>{line_total}€</b>',
        'cart_item_discount_detail': '      ↳ Promo discount: −<code>{amount}€</code> → <b>{final}€</b>',
        'cart_subtotal': '📦 Items subtotal: <b>{subtotal}€</b>',
        'cart_discount_line': '🏷️ Promo ({code} • {percent}%): −<b>{amount}€</b>',
        'cart_balance_applied_line': '💳 Balance applied: −<b>{amount}€</b> → Pay <b>{due}€</b>',
        'cart_total': '🧾 Total due: <b>{total}€</b>',
        'cart_clear': '🧹 Clear my cart',
        'cart_back': '↩️ Back to shop',
        'cart_removed': '{item} removed from your cart.',
        'cart_cleared': 'My cart was cleared.',
        'cart_added': '{item} added to your cart.',
        'cart_item_missing': '❌ Item is unavailable.',
        'cart_checkout': '💳 Checkout all',
        'cart_apply_promo': '🏷️ Apply promo code',
        'cart_remove_promo': '♻️ Remove promo code',
        'cart_manage': '🗂️ Manage items',
        'cart_manage_header': '🗂️ <b>Manage cart items</b>',
        'cart_manage_hint': '<i>Select an item below to remove it from the cart.</i>',
        'cart_manage_line': '{index}. <b>{name}</b> — quantity <code>{quantity}</code>',
        'cart_remove_line': '➖ Remove {name} (x{quantity})',
        'cart_view_summary': '📋 Back to summary',
        'cart_checkout_payment_prompt': '💳 Total due: <b>{total}</b>€. Choose a payment method to continue:',
        'cart_invoice_check': '🔄 Check payment',
        'cart_promo_already': 'Promo code already applied.',
        'cart_promo_unavailable': 'Promo codes do not apply to these items.',
        'cart_promo_prompt': 'Send a promo code for your cart:',
        'cart_promo_removed': 'Promo code removed from cart.',
        'cart_promo_not_applied': 'No promo code applied to remove.',
        'cart_promo_invalid': '❌ Invalid or expired promo code for the cart.',
        'cart_promo_applied': '✅ Promo {code} applied ({percent}%).',
        'cart_promo_blocked': '⚠️ Promo code does not apply to: {items}.',
        'cart_promo_blocked_reason_category': 'category disabled',
        'cart_promo_blocked_reason_assignment': 'not assigned',
        'cart_promo_no_applicable_items': '❌ Promo code cannot be applied to any items in your cart.',
        'cart_insufficient_balance': '❌ Not enough balance. You need {missing}€ more.',
        'cart_lottery_awarded': '🎟️ You received {count} lottery tickets.',
        'cart_checkout_success': '✅ Purchased {count} items for {total}€. Remaining balance: {balance}€.',
        'cart_checkout_success_balance': '✅ Purchased {count} items for {total}€. Balance used: {balance_used}€. Remaining balance: {balance}€.',
        'cart_checkout_failed': '❌ Checkout failed. Try again later.',
        'cart_checkout_partial': '⚠️ These items could not be purchased: {items}.',
        'cart_delivery_caption': '✅ {item}\n💰 Balance: {balance}€\n📦 Purchases: {purchases}',
        'cart_delivery_text': '✅ {item}\n💰 Balance: {balance}€\n📦 Purchases: {purchases}\n\n{value}',
        'cart_notify_restock': '🔔 Remind me',
        'cart_out_of_stock_removed': '⚠️ {item} was removed because it is out of stock.',
        'cart_quantity_adjusted': 'ℹ️ {item} quantity adjusted to {quantity} due to low stock.',
        'games': '🎮 Games',
        'blackjack': '🃏 Blackjack',
        'coinflip': '🪙 Coinflip',
        'coinflip_disabled': '🪙 Coinflip is temporarily unavailable.',
        'achievements': '🏆 Achievements',
        'quests': '🧩 Personalized quests',
        'quests_placeholder': '🔧 Quests are coming soon.',
        'blackjack': '🃏 Blackjack',
        'coinflip': '🪙 Coinflip',
        'find_game': '🔍 Find game',
        'create_game': '➕ Create game',
        'play_bot': '🤖 Play against bot',
        'choose_game': 'Choose a game',
        'choose_side': 'Choose side:',
        'enter_bet': 'Enter bet amount:',
        'heads': 'Heads',
        'tails': 'Tails',
        'not_enough_balance': '❌ Not enough balance',
        'win': 'You won {amount}€!',
        'lose': 'You lost {amount}€.',
        'back': '🔙 Back',
        'create': '✅ Create',
        'join': '✅ Join',
        'waiting_opponent': '⏳ Waiting for an opponent...',
        'no_games': '❌ No games available',
        'join_confirm': 'Join {user} for {bet}€ as {side}?',
        'create_confirm': 'Create game for {bet}€ as {side}?',
        'game_cancelled': 'Game cancelled. Bet refunded.',
        'select_room': 'Select a game to join:',
        'achievement_start': 'Write /start in the bot',
        'achievement_first_purchase': 'Make your first purchase',
        'achievement_first_topup': 'Top up your balance',
        'achievement_first_blackjack': 'Play Blackjack',
        'achievement_first_coinflip': 'Play Coinflip',
        'achievement_gift_sent': 'Send a gift',
        'achievement_first_referral': 'Invite a friend',
        'achievement_five_purchases': 'Buy 5 items',
        'achievement_streak_three': '3-day purchase streak',
        'achievement_ten_referrals': 'Refer 10 friends',
        'achievement_unlocked': '🏆 Achievement unlocked: {name}',
        'show_unlocked': 'Show Unlocked',
        'show_locked': 'Show Locked',
        'level_up': '🎉 Congratulations! You reached {level}.',



    },
    'ru': {
        'hello': '👋 Привет, {user}!',
        'balance': '💰 Баланс: {balance} EUR',
        'overpay': '💳 Отправьте точную сумму. Переплаты будут зачислены.',
        'shop': '🛍 Магазин',
        'profile': '👤 Профиль',
        'top_up': '💸 Пополнить',
        'channel': '📢 Канал',
        'price_list': '💲 Прайс-лист',
        'language': '🌐 Язык',
        'admin_panel': '🎛 Админ панель',
        'help': '❓ Помощь',
        'help_info': (
            'Используйте главное меню для работы с ботом:\n'
            '🛍 Магазин – просматривайте категории и выбирайте товар.\n'
            '   • Выберите товар и подтвердите покупку.\n'
            '👤 Профиль – ваш баланс и купленные товары.\n'
            '💸 Пополнить – выберите способ оплаты и следуйте инструкциям.\n'
            '🌐 Язык – сменить язык интерфейса.\n'
            '🎁 Купленные товары – доступны в профиле после покупки.\n'
            'Если нужна помощь, обратитесь к {helper}.'
        ),
        'admin_help_info': (
            'Функции админ-панели:\n'
            '🛠 Назначить ассистентов – управление помощниками.\n'
            '👔 Назначить владельцев – выдача роли владельца выбранному аккаунту.\n'
            '📦 Просмотр склада – список товаров и удаление остатков.\n'
            '🏪 Parduotuvės valdymas – управление магазином.\n'
            '👥 Vartotojų valdymas – управление пользователями.\n'
            '📢 Pranešimų siuntimas – рассылка сообщений.'
        ),
        'assistant_help_info': (
            'Функции панели ассистента:\n'
            '🖼 Привязать фото – добавление фотографий к товарам.\n'
            'Используйте "Назад в меню" для возврата.'
        ),
        'passwords_menu_title': '🔐 Управление паролями',
        'passwords_generate_prompt': 'Сколько паролей сгенерировать?',
        'passwords_generate_invalid': 'Введите корректное число.',
        'passwords_generate_limit': 'Введите число от 1 до 100.',
        'passwords_generated': 'Сгенерировано {count} паролей:',
        'passwords_no_categories': 'Нет доступных основных категорий.',
        'passwords_lock_title': '🔒 Блокировка основных категорий',
        'passwords_lock_applied': 'Категория "{category}" заблокирована.',
        'passwords_lock_removed': 'Категория "{category}" разблокирована.',
        'passwords_view_users_title': '👥 Пользователи с паролями',
        'passwords_no_user_entries': 'Пока ни один пользователь не использовал пароль.',
        'passwords_user_overview': 'Пользователь {user}',
        'passwords_user_entry': '{category}: <code>{password}</code> ({status}) — {updated}',
        'passwords_user_entry_changed': 'свой',
        'passwords_user_entry_generated': 'сгенерирован',
        'passwords_user_deleted': 'Пароль удалён.',
        'passwords_admin_change_prompt': 'Отправьте новый пароль для {user} в категории {category}:',
        'passwords_admin_change_done': 'Пароль для {user} в категории {category} обновлён.',
        'passwords_change_empty': 'Пароль не может быть пустым.',
        'passwords_change_too_long': 'Пароль должен содержать не более 64 символов.',
        'passwords_locked': 'Категория "{category}" заблокирована.',
        'passwords_prompt': 'Введите пароль для категории {category}:',
        'passwords_invalid': 'Неверный пароль. Попробуйте ещё раз.',
        'passwords_valid': 'Пароль принят для {category}.',
        'passwords_change_prompt': 'Отправьте новый пароль для {category}:',
        'passwords_change_done': 'Пароль для {category} обновлён. Новый пароль:\n<code>{password}</code>',
        'passwords_keep': 'Оставить пароль',
        'passwords_change': 'Изменить пароль',
        'passwords_continue': '➡️ Продолжить',
        'choose_language': 'Пожалуйста, выберите язык',
        'invoice_message': (
            '🧾 <b>Создан инвойс на оплату</b>\n\n'
            '<b>Сумма:</b> <code>{amount}</code> {currency}\n'
            '🏦 <b>Адрес оплаты:</b>\n<code>{address}</code>\n\n'
            '⏳ <b>Действителен до:</b> {expires_at} LT\n'
            '⚠️ <b>Оплата должна быть выполнена в течение 15 минут после создания.</b>\n\n'
            '❗️ <b>Важно:</b> Отправьте <u>ровно</u> это количество {currency}.\n\n'
            '✅ <b>Подтверждение произойдет автоматически через вебхук после подтверждения сети.</b>'
        ),
        'cancel': 'Отмена',
        'cancel_payment': '❌ Отменить оплату',
        'payment_successful': '✅ Платёж подтверждён. Баланс пополнен на {amount}€',
        'back_home': 'Назад домой',
        'invoice_cancelled': 'Оплата не завершена/истекла. Ваши товары больше не зарезервированы.',
        'total_purchases': '📦 Всего покупок: {count}',
        'streak': '🔥 Серия: {days} дн.',
        'note': '⚠️ Возврат средств невозможен. Отправляйте точную сумму, недоплаты не подтверждаются.',
        'rate_limited': '⏳ Слишком много запросов. Пожалуйста, подождите.',
        'captcha_prompt': 'Решите уравнение на изображении.',
        'captcha_prompt_fallback': 'Решите это уравнение: {expression} = ?',
        'captcha_failed': '❌ Неверный ответ. Попробуйте снова.',
        'captcha_success': '✅ Капча пройдена!',
        'rate_experience': '⭐ Как вы оцениваете общий опыт?',
        'rate_service': 'Как вы оцениваете качество сервиса?',
        'rate_product': 'Что вы думаете о товаре?',
        'ask_feedback_reason': 'Хотите написать почему?',
        'feedback_reason': 'Пожалуйста, напишите ваш отзыв:',
        'thanks_feedback': 'Спасибо за отзыв!',
        'confirm_purchase': 'Подтвердить покупку {item} за {price}€?',
        'purchase_button': 'Купить',
        'buy_now': '💰 Купить сейчас',
        'add_to_cart': '🛒 Добавить в корзину',
        'apply_promo': 'Применить промокод',
        'promo_prompt': 'Введите промокод:',
        'promo_invalid': '❌ Недействительный или просроченный промокод',
        'promo_applied': '✅ Промокод применён. Новая цена: {price}€',
        'promo_not_applicable': '❌ Этот промокод нельзя использовать для данного товара.',
        'yes': '✅ Да',
        'no': '❌ Нет',
        'confirm': '✅ Подтвердить',
        'rerun': '🔄 Перезапустить',
        'assign_more': '✅ Фото добавлено. Добавить ещё?',
        'assign_no_categories': '❌ Нет категорий для добавления медиа.',
        'assign_choose_main': '🖼 Привязка медиа\nВыберите основную категорию:',
        'assign_choose_category': '🖼 Привязка медиа\nВыберите категорию или товар:\nПуть: {path}',
        'assign_empty_branch_button': '⚠️ Пустая ветка',
        'assign_empty_branch': 'В этой ветке нет категорий или товаров.',
        'assign_media_prompt': 'Отправьте фото или видео для <b>{item}</b> (DROPAI):',
        'assign_current_path': 'Путь: <code>{path}</code>',
        'assign_media_invalid': '❌ Отправьте фото или видео.',
        'assign_desc_prompt': 'Напишите описание для этого медиа (KOORDINATES):',
        'purchased_items': '📦 Купленные товары',
        'purchased_items': '🎁 Купленные товары',
        'back_to_menu': '🔙 Назад в меню',
        'users_tickets': '🎟️ Билеты пользователей:',
        'no_tickets': 'Нет билетов',
        'lottery_winner': '🎉 Победитель: {username}\n🎟️ Билеты: {tickets}\n\n❗️ Подтверждение сбросит все билеты.',
        'lottery_broadcast_prompt': 'Отправить сообщение всем пользователям?',
        'lottery_enter_message': '✉️ Введите сообщение:',
        'lottery_finished': '✅ Лотерея завершена.',
        'no_winner': '❌ Нет победителя',
        'tools': '🧰 Инструменты',
        'lottery': '🎟️ Лотерея',
        'insufficient_rights': 'Недостаточно прав',
        'use_balance_prompt': 'У вас {balance}€. Использовать их для снижения цены?',
        'choose_crypto': 'Выберите способ оплаты:',
        'need_top_up': 'Вам нужно пополнить {missing}€ для покупки. Выберите способ оплаты:',
        'item_reserved': '🔒 Товар зарезервирован для вас на 15 минут.',
        'payment_cancelled': '✅ Платёж отменён. Резерв снят.',
        'top_up_completed': '✅ Пополнение завершено.',
        'lottery_ticket_awarded': '🎟️ Вы получили лотерейный билет.',
        'lottery_tickets': '🎟️ <b>Лотерейные билеты</b> - <code>{tickets}</code>',
        'referral_link': '🤝 <b>Реферальная ссылка</b> - <code>{link}</code>',
        'referrals': '👥 <b>Рефералы</b> - {count}',
        'referral_earnings': '💰 <b>Заработок с рефералов</b> - <code>{amount}</code> €',
        'referral_reward': '🎉 Ваш реферал {user} совершил покупку - вы получили {amount}€!',
        'gift': '🎀 Подарок',
        'gift_prompt': 'Кому вы хотите подарить товар?',
        'gift_user_not_found': '❌ Пользователь не найден.',
        'gift_select_category': '🎀 Выберите товар для подарка пользователю {user}:',
        'gift_sent': '🎀 Подарок отправлен пользователю {user}!',
        'gift_received': '🎀 Вы получили {item} от {user}!',
        'catalog_editor_menu_title': '🛠️ Меню редактирования каталога',
        'catalog_editor_button_main': '✏️ Редактировать основную категорию',
        'catalog_editor_button_category': '✏️ Редактировать категорию/подкатегорию',
        'catalog_editor_button_item': '✏️ Редактировать товар',
        'catalog_buttons_overview': '🔘 Редактор кнопок\n\nТекущая схема:\n{layout}\n\nВыберите кнопку для изменения или сбросьте настройки.',
        'catalog_buttons_preview_empty': 'Кнопки ещё не настроены.',
        'catalog_buttons_status_active': 'Активна',
        'catalog_buttons_status_hidden': 'Скрыта',
        'catalog_buttons_action_reset': '♻️ Сбросить по умолчанию',
        'catalog_buttons_action_text': '🔤 Изменить название',
        'catalog_buttons_action_position': '📐 Изменить позицию',
        'catalog_buttons_action_toggle_off': '🚫 Скрыть кнопку',
        'catalog_buttons_action_toggle_on': '✅ Показать кнопку',
        'catalog_buttons_action_link': '🔗 Обновить ссылку канала',
        'catalog_buttons_button_info': 'Кнопка: {name}\nРяд: {row}\nКолонка: {column}\nСтатус: {status}',
        'catalog_buttons_button_actions': 'Выберите действие ниже для этой кнопки.',
        'catalog_buttons_column_left': 'Слева',
        'catalog_buttons_column_right': 'Справа',
        'catalog_buttons_position_label': 'Ряд {row} • {column}',
        'catalog_buttons_position_new_suffix': '(новый ряд)',
        'catalog_buttons_position_title': 'Выберите новую позицию для {name}:',
        'catalog_buttons_prompt_text': 'Отправьте новый текст для {name}:',
        'catalog_buttons_prompt_link': 'Отправьте новую ссылку для {name} (введите "-" чтобы очистить и использовать значение по умолчанию):',
        'catalog_buttons_toggle_enabled': 'Кнопка теперь отображается.',
        'catalog_buttons_toggle_disabled': 'Кнопка скрыта.',
        'catalog_buttons_invalid_position': 'Выбрана неверная позиция.',
        'catalog_buttons_position_same': 'Кнопка уже находится в этом месте.',
        'catalog_buttons_position_updated': 'Позиция кнопки обновлена.',
        'catalog_buttons_reset_prompt': 'Сбросить расположение кнопок к значениям по умолчанию?',
        'catalog_buttons_reset_done': 'Схема восстановлена по умолчанию.',
        'catalog_buttons_invalid_text': 'Текст не может быть пустым.',
        'catalog_buttons_text_too_long': 'Текст должен быть не длиннее 64 символов.',
        'catalog_buttons_text_updated': 'Название кнопки обновлено.',
        'catalog_buttons_link_updated': 'Ссылка канала обновлена.',
        'catalog_buttons_link_cleared': 'Ссылка канала очищена. Будет использоваться значение по умолчанию.',
        'catalog_buttons_invalid_link': 'Укажите корректную ссылку или "-" для очистки.',
        'catalog_no_main_categories': '❌ Нет основных категорий. Сначала создайте хотя бы одну.',
        'catalog_no_categories_available': '❌ Нет категорий. Сначала создайте основную категорию.',
        'state_enabled': '✅ Включено',
        'state_disabled': '❌ Выключено',
        'catalog_select_category_first': 'Сначала выберите категорию',
        'catalog_text_intro': 'Выберите язык для редактирования сообщения главного меню.',
        'catalog_text_language_en': '🇬🇧 Английский',
        'catalog_text_language_ru': '🇷🇺 Русский',
        'catalog_text_language_lt': '🇱🇹 Литовский',
        'catalog_text_preview_title': 'Сообщение главного меню ({language}):',
        'catalog_text_placeholders': 'Доступные плейсхолдеры:\n{placeholders}',
        'catalog_text_action_edit': '✏️ Обновить текст',
        'catalog_text_action_reset': '♻️ Сбросить по умолчанию',
        'catalog_text_prompt': (
            'Отправьте новое сообщение главного меню для <b>{language}</b>.\n\n'
            'Плейсхолдеры:\n{placeholders}'
        ),
        'catalog_text_placeholder_user': 'упоминание пользователя со ссылкой на профиль',
        'catalog_text_placeholder_balance': 'числовой баланс (например, 0.00)',
        'catalog_text_placeholder_currency': 'код валюты (например, EUR)',
        'catalog_text_placeholder_purchases': 'общее число завершённых покупок',
        'catalog_text_placeholder_status': 'статус лояльности с эмодзи',
        'catalog_text_placeholder_streak_line': 'готовая строка серии с эмодзи',
        'catalog_text_placeholder_streak_days': 'количество дней в текущей серии',
        'catalog_text_placeholder_note': 'стандартное уведомление о точной сумме платежа',
        'catalog_emojis_title': '✨ Редактор эмодзи',
        'catalog_emojis_help': 'Настройте эмодзи, которые видят пользователи. Изменения применяются сразу.',
        'catalog_emojis_empty': 'Активных замен нет.',
        'catalog_emojis_list_intro': 'Текущие замены:',
        'catalog_emojis_override_line': '{original} → {replacement}',
        'catalog_emojis_add_override': '➕ Добавить или обновить замену',
        'catalog_emojis_reset_all': '♻️ Очистить все замены',
        'catalog_emojis_prompt_original': 'Отправьте эмодзи, который нужно заменить.',
        'catalog_emojis_prompt_replacement': (
            'Отправьте новый эмодзи для {original}. Введите <code>default</code>, чтобы удалить замену.'
        ),
        'catalog_emojis_invalid_emoji': 'Отправьте один эмодзи или введите <code>default</code>.',
        'catalog_emojis_updated': 'Эмодзи обновлён: {original} → {replacement}',
        'catalog_emojis_removed': 'Замена удалена для {original}.',
        'catalog_emojis_reset': 'Все замены эмодзи очищены.',
        'catalog_emojis_remove_button': '🗑 {original} → {replacement}',
        'catalog_text_saved': '✅ Текст главного меню обновлён.',
        'catalog_text_reset_done': '✅ Текст главного меню сброшен к стандартному.',
        'catalog_text_empty': '⚠️ Текст не может быть пустым.',
        'catalog_name_empty': '⚠️ Название не может быть пустым',
        'catalog_name_exists': '❌ Такая категория уже существует',
        'catalog_select_main_categories': 'Выберите основные категории для новой категории:',
        'catalog_category_creation_cancelled': '❌ Создание категории отменено',
        'catalog_need_main_category': 'Выберите хотя бы одну основную категорию',
        'catalog_category_name_prompt': 'Введите название категории для "{parent}" ({index}/{total}):',
        'catalog_select_parents': 'Выберите родительские категории:',
        'catalog_select_parents_path': 'Выберите родительские категории:\nТекущий путь: {path}',
        'catalog_subcategory_creation_cancelled': '❌ Создание подкатегории отменено',
        'catalog_subcategory_name_prompt': 'Введите название подкатегории для "{parent}" ({index}/{total}):',
        'catalog_select_subcategories': 'Выберите подкатегории для товара:',
        'catalog_select_subcategories_path': 'Выберите подкатегории для товара:\nТекущий путь: {path}',
        'catalog_item_name_for_destination': 'Введите название товара для {path} ({index}/{total}):',
        'catalog_item_name_hint': 'Отправьте уникальное название для этой локации или нажмите ниже, чтобы оставить «{name}».',
        'catalog_item_name_keep': 'Оставить «{name}»',
        'catalog_item_name_invalid': '⚠️ Название не может быть пустым.',
        'multi_select_empty': '⚠️ Пусто',
        'multi_select_up': '⬆️ Вверх',
        'action_done': '✅ Готово',
        'action_clear': '🧹 Очистить',
        'action_cancel': '🔙 Отменить',
        'multi_select_no_children': 'В этой ветке нет доступных вариантов.',
        'multi_select_target_missing': 'Этот вариант больше недоступен.',
        'multi_select_need_category': 'Выберите хотя бы одну категорию',
        'multi_select_depth_limit': 'Достигнута максимальная глубина. Вернитесь назад.',
        'catalog_item_creation_cancelled': '❌ Создание товара отменено',
        'catalog_items_created': '✅ Товары созданы:\n{summary}',
        'catalog_item_update_cancelled': '❌ Обновление товара отменено',
        'catalog_update_select_root': 'Выберите категорию для редактирования товара:',
        'catalog_update_select_branch': 'Выберите подкатегорию или товар:\nТекущий путь: {path}',
        'catalog_update_branch_empty_button': '⚠️ Пустая ветка',
        'catalog_update_branch_empty': 'В этой ветке нет товаров.',
        'catalog_category_update_cancelled': '❌ Изменение категории отменено',
        'catalog_category_rename_prompt': 'Введите новое название для "{name}":',
        'catalog_category_updated': '✅ Категория "{old}" переименована в "{new}".',
        'catalog_update_name_prompt': 'Введите новое название для "{name}":',
        'catalog_update_description_prompt': 'Введите описание для "{name}":',
        'catalog_update_price_prompt': 'Введите цену для "{name}":',
        'catalog_invalid_price': '⚠️ Некорректное значение цены.',
        'catalog_item_update_complete': '✅ Позиция обновлена.',
        'catalog_update_preview_prompt': '✅ Позиция обновлена. Обновить превью для <b>{name}</b>?',
        'catalog_update_preview_send': 'Отправьте новое превью для <b>{name}</b>.',
        'catalog_update_preview_saved': '✅ Превью обновлено.',
        'catalog_update_preview_cancelled': 'Превью оставлено без изменений.',
        'catalog_update_preview_invalid': '❌ Отправьте фотографию для превью.',
        'stock_notify': '📦 Уведомления о наличии',
        'choose_product_notify': 'Выберите товар для уведомления о появлении:',
        'no_out_of_stock': '✅ Все товары в наличии.',
        'stock_subscribed': '🔔 Мы уведомим вас, когда {item} появится.',
        'stock_already_subscribed': 'ℹ️ Вы уже ожидаете {item}.',
        'stock_back_in': '📦 {item} снова в наличии!',

        'choose_subcategory': '🏘️ Выберите район:',
        'select_product': '🏪 Выберите товар',
        'shop_categories': '🏪 Категории магазина',
        'view_cart': '🧺 Моя корзина',
        'cart_empty': '🧺 Ваша корзина пуста.',
        'cart_header': '🧺 <b>Моя корзина</b>',
        'cart_divider': '<code>────────────────────</code>',
        'cart_summary_hint': '<i>Проверьте товары перед оформлением.</i>',
        'cart_item_line': '{index}. <b>{name}</b>\n   ×<code>{quantity}</code> • <code>{unit_price}€</code> → <b>{line_total}€</b>',
        'cart_item_discount_detail': '      ↳ Скидка по промокоду: −<code>{amount}€</code> → <b>{final}€</b>',
        'cart_subtotal': '📦 Сумма товаров: <b>{subtotal}€</b>',
        'cart_discount_line': '🏷️ Промокод ({code} • {percent}%): −<b>{amount}€</b>',
        'cart_balance_applied_line': '💳 Списано с баланса: −<b>{amount}€</b> → К оплате <b>{due}€</b>',
        'cart_total': '🧾 К оплате: <b>{total}€</b>',
        'cart_clear': '🧹 Очистить корзину',
        'cart_back': '↩️ Назад в магазин',
        'cart_removed': '{item} удалён из вашей корзины.',
        'cart_cleared': 'Корзина очищена.',
        'cart_added': '{item} добавлен в корзину.',
        'cart_item_missing': '❌ Товар недоступен.',
        'cart_checkout': '💳 Оплатить всё',
        'cart_apply_promo': '🏷️ Применить промокод',
        'cart_remove_promo': '♻️ Удалить промокод',
        'cart_manage': '🗂️ Управлять товарами',
        'cart_manage_header': '🗂️ <b>Управление корзиной</b>',
        'cart_manage_hint': '<i>Выберите товар, чтобы удалить его из корзины.</i>',
        'cart_manage_line': '{index}. <b>{name}</b> — количество <code>{quantity}</code>',
        'cart_remove_line': '➖ Удалить {name} (x{quantity})',
        'cart_view_summary': '📋 Назад к обзору',
        'cart_checkout_payment_prompt': '💳 К оплате: <b>{total}</b>€. Выберите способ оплаты:',
        'cart_invoice_check': '🔄 Проверить оплату',
        'cart_promo_already': 'Промокод уже применён.',
        'cart_promo_unavailable': 'К этим товарам промокод не применяется.',
        'cart_promo_prompt': 'Отправьте промокод для корзины:',
        'cart_promo_removed': 'Промокод удалён из корзины.',
        'cart_promo_not_applied': 'Нет применённого промокода для удаления.',
        'cart_promo_invalid': '❌ Неверный или просроченный промокод для корзины.',
        'cart_promo_applied': '✅ Промокод {code} применён ({percent}%).',
        'cart_promo_blocked': '⚠️ Промокод не действует на: {items}.',
        'cart_promo_blocked_reason_category': 'категория запрещает',
        'cart_promo_blocked_reason_assignment': 'не назначено',
        'cart_promo_no_applicable_items': '❌ Промокод не может быть применён ни к одному товару в корзине.',
        'cart_insufficient_balance': '❌ Недостаточно средств. Не хватает {missing}€.',
        'cart_lottery_awarded': '🎟️ Вы получили {count} лотерейных билета.',
        'cart_checkout_success': '✅ Куплено товаров: {count} на сумму {total}€. Остаток: {balance}€.',
        'cart_checkout_success_balance': '✅ Куплено товаров: {count} на сумму {total}€. Списано с баланса: {balance_used}€. Остаток: {balance}€.',
        'cart_checkout_failed': '❌ Не удалось оформить покупку. Попробуйте позже.',
        'cart_checkout_partial': '⚠️ Не удалось купить: {items}.',
        'cart_delivery_caption': '✅ {item}\n💰 Баланс: {balance}€\n📦 Покупок: {purchases}',
        'cart_delivery_text': '✅ {item}\n💰 Баланс: {balance}€\n📦 Покупок: {purchases}\n\n{value}',
        'cart_notify_restock': '🔔 Напомнить мне',
        'cart_out_of_stock_removed': '⚠️ {item} удалён, потому что закончился на складе.',
        'cart_quantity_adjusted': 'ℹ️ Количество {item} изменено на {quantity} из-за остатка.',
        'games': '🎮 Игры',
        'blackjack': '🃏 Блэкджек',
        'coinflip': '🪙 Монетка',
        'coinflip_disabled': '🪙 Монетка временно недоступна.',
        'achievements': '🏆 Достижения',
        'quests': '🧩 Персональные задания',
        'quests_placeholder': '🔧 Задания скоро появятся.',
        'find_game': '🔍 Найти игру',
        'create_game': '➕ Создать игру',
        'play_bot': '🤖 Играть с ботом',
        'choose_game': 'Выберите игру',
        'choose_side': 'Выберите сторону:',
        'enter_bet': 'Введите сумму ставки:',
        'heads': 'Орел',
        'tails': 'Решка',
        'not_enough_balance': '❌ Недостаточно средств',
        'win': 'Вы выиграли {amount}€!',
        'lose': 'Вы проиграли {amount}€.',
        'back': '🔙 Назад',
        'create': '✅ Создать',
        'join': '✅ Присоединиться',
        'waiting_opponent': '⏳ Ожидание оппонента...',
        'no_games': '❌ Нет доступных игр',
        'join_confirm': 'Играть с {user} на {bet}€ за {side}?',
        'create_confirm': 'Создать игру на {bet}€ за {side}?',
        'game_cancelled': 'Игра отменена. Ставка возвращена.',
        'select_room': 'Выберите игру для присоединения:',
        'achievement_start': 'Напишите /start боту',
        'achievement_first_purchase': 'Совершите первую покупку',
        'achievement_first_topup': 'Пополните баланс',

        'achievement_first_blackjack': 'Сыграйте в Блэкджек',
        'achievement_first_coinflip': 'Сыграйте в Монетку',
        'achievement_gift_sent': 'Отправьте подарок',
        'achievement_first_referral': 'Пригласите друга',
        'achievement_five_purchases': 'Купите 5 товаров',
        'achievement_streak_three': 'Покупайте 3 дня подряд',
        'achievement_ten_referrals': 'Пригласите 10 друзей',
        'achievement_unlocked': '🏆 Достижение получено: {name}',
        'show_unlocked': 'Показать полученные',
        'show_locked': 'Показать неполученные',
        'level_up': '🎉 Поздравляем! Вы достигли уровня {level}.',

    },
    'lt': {
        'hello': '👋 Sveiki, {user}!',
        'balance': '💰 Balansas: {balance} EUR',
        'overpay': '💳 Siųskite tikslią sumą. Permokos bus įskaitytos.',
        'shop': '🛍 Parduotuvė',
        'profile': '👤 Profilis',
        'top_up': '💸 Papildyti',
        'channel': '📢 Kanalas',
        'price_list': '💲 Kainoraštis',
        'language': '🌐 Kalba',
        'admin_panel': '🎛 Admin pultas',
        'help': '❓ Pagalba',
        'help_info': (
            'Naudokite pagrindinį meniu darbui su botu:\n'
            '🛍 Parduotuvė – naršykite kategorijas ir pasirinkite prekę.\n'
            '   • Pasirinkite prekę ir patvirtinkite pirkimą.\n'
            '👤 Profilis – jūsų balansas ir nupirktos prekės.\n'
            '💸 Papildyti – pasirinkite mokėjimo būdą ir vykdykite instrukcijas.\n'
            '🌐 Kalba – pakeisti sąsajos kalbą.\n'
            '🎁 Nupirktos prekės – matomos profilyje po pirkimo.\n'
            'Jei reikia pagalbos, susisiekite su {helper}.'
        ),
        'admin_help_info': (
            'Admin pulto funkcijos:\n'
            '🛠 Asistentų priskyrimas – valdykite asistentų paskyras.\n'
            '👔 Savininkų priskyrimas – suteikite savininko rolę pasirinktai paskyrai.\n'
            '📦 Peržiūrėti likučius – naršykite prekes ir trinkite likučius.\n'
            '🏪 Parduotuvės valdymas – prekių ir kategorijų valdymas.\n'
            '👥 Vartotojų valdymas – naudotojų balansai ir rolės.\n'
            '📢 Pranešimų siuntimas – siųsti žinutes vartotojams.'
        ),
        'assistant_help_info': (
            'Asistento pulto funkcijos:\n'
            '🖼 Nuotraukų priskyrimas – pridėkite nuotraukas prie prekių.\n'
            'Naudokite „Atgal į meniu“ norėdami grįžti.'
        ),
        'choose_language': 'Pasirinkite kalbą',
        'invoice_message': (
            '🧾 <b>Sukurta mokėjimo sąskaita</b>\n\n'
            '<b>Suma:</b> <code>{amount}</code> {currency}\n'
            '🏦 <b>Mokėjimo adresas:</b>\n<code>{address}</code>\n\n'
            '⏳ <b>Galioja iki:</b> {expires_at} LT\n'
            '⚠️ <b>Mokėjimą reikia atlikti per 15 minučių nuo sąskaitos sukūrimo.</b>\n\n'
            '❗️ <b>Svarbu:</b> Nusiųskite <u>tiksliai</u> tiek {currency} į šį adresą.\n\n'
            '✅ <b>Patvirtinimas vyks automatiškai per webhook po tinklo patvirtinimo.</b>'
        ),
        'cancel': 'Atšaukti',
        'cancel_payment': '❌ Atšaukti mokėjimą',
        'payment_successful': '✅ Mokėjimas patvirtintas. Balansas padidintas {amount}€',
        'back_home': 'Grįžti į pradžią',
        'invoice_cancelled': 'Mokėjimas nepavyko/baigėsi. Jūsų prekės nebėra rezervuotos.',
        'total_purchases': '📦 Viso pirkinių: {count}',
        'streak': '🔥 Serija: {days} d.',
        'note': '⚠️ Pastaba: grąžinimų nėra. Įsitikinkite, kad siunčiate tikslią sumą, nes nepakankamos sumos nebus patvirtintos.',
        'rate_limited': '⏳ Per daug užklausų. Prašome palaukti.',
        'captcha_prompt': 'Išspręskite paveikslėlyje pateiktą lygtį.',
        'captcha_prompt_fallback': 'Išspręskite šią lygtį: {expression} = ?',
        'captcha_failed': '❌ Neteisingas atsakymas. Bandykite dar kartą.',
        'captcha_success': '✅ Captcha sėkmingai įvykdyta!',
        'rate_experience': '⭐ Kaip vertinate bendrą patirtį?',
        'rate_service': 'Kaip vertinate aptarnavimo kokybę?',
        'rate_product': 'Kokia jūsų nuomonė apie produktą?',
        'ask_feedback_reason': 'Ar norėtumėte parašyti kodėl?',
        'feedback_reason': 'Prašome parašyti atsiliepimą:',
        'thanks_feedback': 'Ačiū už atsiliepimą!',
        'confirm_purchase': 'Patvirtinti {item} pirkimą už {price}€?',
        'purchase_button': 'Pirkti',
        'buy_now': '💰 Pirkti dabar',
        'add_to_cart': '🛒 Pridėti į krepšelį',
        'apply_promo': 'Taikyti nuolaidos kodą',
        'promo_prompt': 'Įveskite nuolaidos kodą:',
        'promo_invalid': '❌ Neteisingas arba pasibaigęs kodas',
        'promo_applied': '✅ Kodas pritaikytas. Nauja kaina: {price}€',
        'promo_not_applicable': '❌ Šio nuolaidos kodo negalima naudoti šiai prekei.',
        'yes': '✅ Taip',
        'no': '❌ Ne',
        'confirm': '✅ Patvirtinti',
        'rerun': '🔄 Perleisti',
        'assign_more': '✅ Nuotrauka pridėta. Pridėti dar?',
        'assign_no_categories': '❌ Nėra kategorijų nuotraukoms priskirti.',
        'assign_choose_main': '🖼 Nuotraukų priskyrimas\nPasirinkite pagrindinę kategoriją:',
        'assign_choose_category': '🖼 Nuotraukų priskyrimas\nPasirinkite kategoriją ar prekę:\nKelias: {path}',
        'assign_empty_branch_button': '⚠️ Tuščia šaka',
        'assign_empty_branch': 'Šioje šakoje nėra kategorijų ar prekių.',
        'assign_media_prompt': 'Siųskite nuotrauką ar vaizdo įrašą prekei <b>{item}</b> (DROPAI):',
        'assign_current_path': 'Kelias: <code>{path}</code>',
        'assign_media_invalid': '❌ Siųskite nuotrauką arba vaizdo įrašą.',
        'assign_desc_prompt': 'Parašykite šios medijos aprašymą (KOORDINATES):',
        'purchased_items': '📦 Įsigytos prekės',
        'purchased_items': '🎁 Įsigytos prekės',
        'back_to_menu': '🔙 Atgal į meniu',
        'users_tickets': '🎟️ Vartotojų bilietai:',
        'no_tickets': 'Nėra bilietų',
        'lottery_winner': '🎉 Nugalėtojas: {username}\n🎟️ Bilietai: {tickets}\n\n❗️ Patvirtinus, visi bilietai bus ištrinti.',
        'lottery_broadcast_prompt': 'Siųsti pranešimą visiems vartotojams?',
        'lottery_enter_message': '✉️ Įveskite pranešimą:',
        'lottery_finished': '✅ Loterija baigta.',
        'no_winner': '❌ Nėra nugalėtojo',
        'tools': '🧰 Įrankiai',
        'lottery': '🎟️ Loterija',
        'insufficient_rights': 'Nepakanka teisių',
        'passwords_menu_title': '🔐 Slaptažodžių valdymas',
        'passwords_generate_prompt': 'Kiek slaptažodžių sugeneruoti?',
        'passwords_generate_invalid': 'Įveskite teisingą skaičių.',
        'passwords_generate_limit': 'Įveskite skaičių nuo 1 iki 100.',
        'passwords_generated': 'Sugeneruota {count} slaptažodžių:',
        'passwords_no_categories': 'Nėra pagrindinių kategorijų.',
        'passwords_lock_title': '🔒 Užrakinti pagrindines kategorijas',
        'passwords_lock_applied': 'Kategorija „{category}“ užrakinta.',
        'passwords_lock_removed': 'Kategorija „{category}“ atrakinta.',
        'passwords_view_users_title': '👥 Vartotojai, naudoję slaptažodžius',
        'passwords_no_user_entries': 'Dar nėra vartotojų su slaptažodžiais.',
        'passwords_user_overview': 'Vartotojas {user}',
        'passwords_user_entry': '{category}: <code>{password}</code> ({status}) — {updated}',
        'passwords_user_entry_changed': 'pakeistas',
        'passwords_user_entry_generated': 'sugeneruotas',
        'passwords_user_deleted': 'Slaptažodis pašalintas.',
        'passwords_admin_change_prompt': 'Įrašykite naują slaptažodį vartotojui {user} kategorijoje {category}:',
        'passwords_admin_change_done': 'Atnaujintas {user} slaptažodis kategorijoje {category}.',
        'passwords_change_empty': 'Slaptažodis negali būti tuščias.',
        'passwords_change_too_long': 'Slaptažodis turi būti iki 64 simbolių.',
        'passwords_locked': 'Kategorija „{category}“ užrakinta.',
        'passwords_prompt': 'Įveskite slaptažodį kategorijai {category}:',
        'passwords_invalid': 'Neteisingas slaptažodis. Bandykite dar kartą.',
        'passwords_valid': 'Slaptažodis priimtas kategorijai {category}.',
        'passwords_change_prompt': 'Įveskite naują slaptažodį kategorijai {category}:',
        'passwords_change_done': 'Slaptažodis kategorijai {category} atnaujintas. Naujas slaptažodis:\n<code>{password}</code>',
        'passwords_keep': 'Palikti',
        'passwords_change': 'Keisti slaptažodį',
        'passwords_continue': '➡️ Tęsti',
        'use_balance_prompt': 'Turite {balance}€. Panaudoti juos kainai sumažinti?',
        'choose_crypto': 'Pasirinkite mokėjimo būdą:',
        'need_top_up': 'Turite papildyti {missing}€ šiam pirkiniui. Pasirinkite mokėjimo būdą:',
        'item_reserved': '🔒 Prekė rezervuota jums 15 minučių.',
        'payment_cancelled': '✅ Mokėjimas atšauktas. Rezervuotos prekės atlaisvintos.',
        'top_up_completed': '✅ Papildymas baigtas.',
        'lottery_ticket_awarded': '🎟️ Gavote loterijos bilietą.',
        'lottery_tickets': '🎟️ <b>Loterijos bilietai</b> - <code>{tickets}</code>',
        'referral_link': '🤝 <b>Pakvietimo nuoroda</b> - <code>{link}</code>',
        'referrals': '👥 <b>Pakviesti vartotojai</b> - {count}',
        'referral_earnings': '💰 <b>Uždirbta iš pakvietimų</b> - <code>{amount}</code> €',
        'referral_reward': '🎉 Jūsų pakviestas vartotojas {user} įsigijo prekę – gavote {amount}€!',
        'gift': '🎀 Dovanoti',
        'gift_prompt': 'Kam norite padovanoti produktą?',
        'gift_user_not_found': '❌ Vartotojas nerastas.',
        'gift_select_category': '🎀 Pasirinkite produktą dovanai naudotojui {user}:',
        'gift_sent': '🎀 Dovana išsiųsta naudotojui {user}!',
        'gift_received': '🎀 Gavote {item} nuo {user}!',
        'catalog_editor_menu_title': '🛠️ Katalogo redagavimo meniu',
        'catalog_editor_button_main': '✏️ Redaguoti pagrindinę kategoriją',
        'catalog_editor_button_category': '✏️ Redaguoti kategoriją/subkategoriją',
        'catalog_editor_button_item': '✏️ Redaguoti prekę',
        'catalog_buttons_overview': '🔘 Mygtukų redagavimas\n\nDabartinis išdėstymas:\n{layout}\n\nPasirinkite mygtuką arba atkurkite numatytą išdėstymą.',
        'catalog_buttons_preview_empty': 'Mygtukai dar nenustatyti.',
        'catalog_buttons_status_active': 'Aktyvus',
        'catalog_buttons_status_hidden': 'Paslėptas',
        'catalog_buttons_action_reset': '♻️ Atkurti numatytą',
        'catalog_buttons_action_text': '🔤 Keisti pavadinimą',
        'catalog_buttons_action_position': '📐 Keisti vietą',
        'catalog_buttons_action_toggle_off': '🚫 Paslėpti mygtuką',
        'catalog_buttons_action_toggle_on': '✅ Rodyti mygtuką',
        'catalog_buttons_action_link': '🔗 Atnaujinti kanalo nuorodą',
        'catalog_buttons_button_info': 'Mygtukas: {name}\nEilė: {row}\nStulpelis: {column}\nBūsena: {status}',
        'catalog_buttons_button_actions': 'Pasirinkite, ką norite redaguoti.',
        'catalog_buttons_column_left': 'Kairė',
        'catalog_buttons_column_right': 'Dešinė',
        'catalog_buttons_position_label': '{row} eilė • {column}',
        'catalog_buttons_position_new_suffix': '(nauja eilė)',
        'catalog_buttons_position_title': 'Pasirinkite naują {name} vietą:',
        'catalog_buttons_prompt_text': 'Įrašykite naują {name} pavadinimą:',
        'catalog_buttons_prompt_link': 'Įrašykite naują {name} nuorodą (įrašykite "-" jei norite naudoti numatytą):',
        'catalog_buttons_toggle_enabled': 'Mygtukas vėl matomas.',
        'catalog_buttons_toggle_disabled': 'Mygtukas paslėptas.',
        'catalog_buttons_invalid_position': 'Pasirinkta netinkama vieta.',
        'catalog_buttons_position_same': 'Mygtukas jau yra šioje vietoje.',
        'catalog_buttons_position_updated': 'Mygtuko vieta atnaujinta.',
        'catalog_buttons_reset_prompt': 'Ar atkurti mygtukų išdėstymą į numatytą?',
        'catalog_buttons_reset_done': 'Išdėstymas atkurtas.',
        'catalog_buttons_invalid_text': 'Pavadinimas negali būti tuščias.',
        'catalog_buttons_text_too_long': 'Pavadinimas turi būti iki 64 simbolių.',
        'catalog_buttons_text_updated': 'Mygtuko pavadinimas atnaujintas.',
        'catalog_buttons_link_updated': 'Kanalo nuoroda atnaujinta.',
        'catalog_buttons_link_cleared': 'Kanalo nuoroda išvalyta. Bus naudojama numatytoji.',
        'catalog_buttons_invalid_link': 'Įrašykite galiojančią nuorodą arba "-" jai išvalyti.',
        'catalog_no_main_categories': '❌ Nėra pagrindinių kategorijų. Sukurkite bent vieną.',
        'catalog_no_categories_available': '❌ Nėra kategorijų. Pirmiausia sukurkite pagrindinę kategoriją.',
        'state_enabled': '✅ Įjungta',
        'state_disabled': '❌ Išjungta',
        'catalog_select_category_first': 'Pasirinkite kategoriją',
        'catalog_text_intro': 'Pasirinkite kalbą pagrindinio meniu tekstui redaguoti.',
        'catalog_text_language_en': '🇬🇧 Anglų',
        'catalog_text_language_ru': '🇷🇺 Rusų',
        'catalog_text_language_lt': '🇱🇹 Lietuvių',
        'catalog_text_preview_title': '{language} pagrindinio meniu tekstas:',
        'catalog_text_placeholders': 'Galimi žymekliai:\n{placeholders}',
        'catalog_text_action_edit': '✏️ Atnaujinti tekstą',
        'catalog_text_action_reset': '♻️ Atstatyti numatytąjį',
        'catalog_text_prompt': (
            'Atsiųskite naują pagrindinio meniu tekstą kalbai <b>{language}</b>.\n\n'
            'Žymekliai:\n{placeholders}'
        ),
        'catalog_text_placeholder_user': 'vartotojo paminėjimas su profilio nuoroda',
        'catalog_text_placeholder_balance': 'balanso reikšmė (pvz., 0.00)',
        'catalog_text_placeholder_currency': 'valiutos kodas (pvz., EUR)',
        'catalog_text_placeholder_purchases': 'bendras įsigijimų skaičius',
        'catalog_text_placeholder_status': 'lojalumo statusas su jaustuku',
        'catalog_text_placeholder_streak_line': 'suformatuota serijos eilutė su jaustuku',
        'catalog_text_placeholder_streak_days': 'dienų skaičius dabartinėje serijoje',
        'catalog_text_placeholder_note': 'numatytoji pastaba apie mokėjimo tikslumą',
        'catalog_emojis_title': '✨ Emodžių redaktorius',
        'catalog_emojis_help': 'Keiskite klientams rodomus emodžius. Pakeitimai pritaikomi iškart.',
        'catalog_emojis_empty': 'Šiuo metu pakeitimų nėra.',
        'catalog_emojis_list_intro': 'Dabartiniai pakeitimai:',
        'catalog_emojis_override_line': '{original} → {replacement}',
        'catalog_emojis_add_override': '➕ Pridėti arba atnaujinti pakeitimą',
        'catalog_emojis_reset_all': '♻️ Pašalinti visus pakeitimus',
        'catalog_emojis_prompt_original': 'Atsiųskite emodžį, kurį norite pakeisti.',
        'catalog_emojis_prompt_replacement': (
            'Atsiųskite naują emodžį {original}. Įrašykite <code>default</code>, jei norite grąžinti numatytąjį.'
        ),
        'catalog_emojis_invalid_emoji': 'Įrašykite vieną emodžį arba <code>default</code>.',
        'catalog_emojis_updated': 'Emodžis atnaujintas: {original} → {replacement}',
        'catalog_emojis_removed': 'Pakeitimas pašalintas: {original}.',
        'catalog_emojis_reset': 'Visi emodžių pakeitimai išvalyti.',
        'catalog_emojis_remove_button': '🗑 {original} → {replacement}',
        'catalog_text_saved': '✅ Pagrindinio meniu tekstas atnaujintas.',
        'catalog_text_reset_done': '✅ Pagrindinio meniu tekstas atkurtas į numatytąjį.',
        'catalog_text_empty': '⚠️ Tekstas negali būti tuščias.',
        'catalog_name_empty': '⚠️ Pavadinimas negali būti tuščias',
        'catalog_name_exists': '❌ Tokia kategorija jau egzistuoja',
        'catalog_select_main_categories': 'Pasirinkite pagrindines kategorijas naujai kategorijai:',
        'catalog_category_creation_cancelled': '❌ Kategorijos kūrimas atšauktas',
        'catalog_need_main_category': 'Pasirinkite bent vieną pagrindinę kategoriją',
        'catalog_category_name_prompt': 'Įveskite kategorijos pavadinimą "{parent}" ({index}/{total}):',
        'catalog_select_parents': 'Pasirinkite tėvines kategorijas:',
        'catalog_select_parents_path': 'Pasirinkite tėvines kategorijas:\nDabartinis kelias: {path}',
        'catalog_subcategory_creation_cancelled': '❌ Subkategorijos kūrimas atšauktas',
        'catalog_subcategory_name_prompt': 'Įveskite subkategorijos pavadinimą "{parent}" ({index}/{total}):',
        'catalog_select_subcategories': 'Pasirinkite subkategorijas prekei:',
        'catalog_select_subcategories_path': 'Pasirinkite subkategorijas prekei:\nDabartinis kelias: {path}',
        'catalog_item_name_for_destination': 'Įveskite prekės pavadinimą vietai {path} ({index}/{total}):',
        'catalog_item_name_hint': 'Įrašykite unikalų pavadinimą šiai vietai arba spauskite žemiau ir palikite „{name}“.',
        'catalog_item_name_keep': 'Palikti „{name}“',
        'catalog_item_name_invalid': '⚠️ Pavadinimas negali būti tuščias.',
        'multi_select_empty': '⚠️ Tuščia',
        'multi_select_up': '⬆️ Aukštyn',
        'action_done': '✅ Baigta',
        'action_clear': '🧹 Išvalyti',
        'action_cancel': '🔙 Atšaukti',
        'multi_select_no_children': 'Šioje šakoje nėra pasirinkimų.',
        'multi_select_target_missing': 'Šio pasirinkimo nebėra.',
        'multi_select_need_category': 'Pasirinkite bent vieną kategoriją',
        'multi_select_depth_limit': 'Pasiektas maksimalus gylis. Grįžkite atgal.',
        'catalog_item_creation_cancelled': '❌ Prekės kūrimas atšauktas',
        'catalog_items_created': '✅ Sukurtos prekės:\n{summary}',
        'catalog_item_update_cancelled': '❌ Prekės atnaujinimas atšauktas',
        'catalog_update_select_root': 'Pasirinkite kategoriją prekei redaguoti:',
        'catalog_update_select_branch': 'Pasirinkite subkategoriją ar prekę:\nDabartinis kelias: {path}',
        'catalog_update_branch_empty_button': '⚠️ Tuščia šaka',
        'catalog_update_branch_empty': 'Šioje šakoje nėra prekių.',
        'catalog_category_update_cancelled': '❌ Kategorijos keitimas atšauktas',
        'catalog_category_rename_prompt': 'Įveskite naują pavadinimą „{name}“ kategorijai:',
        'catalog_category_updated': '✅ Kategorija „{old}“ pervadinta į „{new}“.',
        'catalog_update_name_prompt': 'Įveskite naują pavadinimą „{name}“:',
        'catalog_update_description_prompt': 'Įveskite aprašymą „{name}“:',
        'catalog_update_price_prompt': 'Įveskite kainą „{name}“:',
        'catalog_invalid_price': '⚠️ Neteisinga kainos reikšmė.',
        'catalog_item_update_complete': '✅ Prekė atnaujinta.',
        'catalog_update_preview_prompt': '✅ Prekė atnaujinta. Atnaujinti <b>{name}</b> peržiūros nuotrauką?',
        'catalog_update_preview_send': 'Atsiųskite naują peržiūros nuotrauką prekei <b>{name}</b>.',
        'catalog_update_preview_saved': '✅ Peržiūros nuotrauka atnaujinta.',
        'catalog_update_preview_cancelled': 'Peržiūros nuotrauka nepakeista.',
        'catalog_update_preview_invalid': '❌ Atsiųskite nuotrauką peržiūrai.',

        'stock_notify': '📦 Atsargų pranešimai',
        'choose_product_notify': 'Pasirinkite prekę, kurios atsargų laukti:',
        'no_out_of_stock': '✅ Visos prekės turimos.',
        'stock_subscribed': '🔔 Būsite informuoti, kai {item} bus papildyta.',
        'stock_already_subscribed': 'ℹ️ Jūs jau laukiate {item}.',
        'stock_back_in': '📦 {item} vėl sandėlyje!',

        'choose_subcategory': '🏘️ Pasirinkite miestą:',
        'select_product': '🏪 Pasirinkite prekę',
        'shop_categories': '🏪 Parduotuvės kategorijos',
        'view_cart': '🧺 Mano krepšelis',
        'cart_empty': '🧺 Jūsų krepšelis tuščias.',
        'cart_header': '🧺 <b>Mano krepšelis</b>',
        'cart_divider': '<code>────────────────────</code>',
        'cart_summary_hint': '<i>Peržiūrėkite prekes prieš apmokėjimą.</i>',
        'cart_item_line': '{index}. <b>{name}</b>\n   ×<code>{quantity}</code> • <code>{unit_price}€</code> → <b>{line_total}€</b>',
        'cart_item_discount_detail': '      ↳ Nuolaida: −<code>{amount}€</code> → <b>{final}€</b>',
        'cart_subtotal': '📦 Prekių suma: <b>{subtotal}€</b>',
        'cart_discount_line': '🏷️ Nuolaida ({code} • {percent}%): −<b>{amount}€</b>',
        'cart_balance_applied_line': '💳 Pritaikyta balanso: −<b>{amount}€</b> → Mokėti <b>{due}€</b>',
        'cart_total': '🧾 Mokėtina: <b>{total}€</b>',
        'cart_clear': '🧹 Ištuštinti krepšelį',
        'cart_back': '↩️ Grįžti į parduotuvę',
        'cart_removed': 'Prekė {item} pašalinta iš krepšelio.',
        'cart_cleared': 'Krepšelis išvalytas.',
        'cart_added': '{item} pridėta į krepšelį.',
        'cart_item_missing': '❌ Prekė nepasiekiama.',
        'cart_checkout': '💳 Apmokėti viską',
        'cart_apply_promo': '🏷️ Pritaikyti nuolaidos kodą',
        'cart_remove_promo': '♻️ Pašalinti nuolaidos kodą',
        'cart_manage': '🗂️ Tvarkyti prekes',
        'cart_manage_header': '🗂️ <b>Tvarkyti krepšelio prekes</b>',
        'cart_manage_hint': '<i>Pasirinkite prekę, kurią norite pašalinti.</i>',
        'cart_manage_line': '{index}. <b>{name}</b> — kiekis <code>{quantity}</code>',
        'cart_remove_line': '➖ Pašalinti {name} (x{quantity})',
        'cart_view_summary': '📋 Grįžti į suvestinę',
        'cart_checkout_payment_prompt': '💳 Mokėtina suma: <b>{total}</b>€. Pasirinkite mokėjimo būdą:',
        'cart_invoice_check': '🔄 Patikrinti mokėjimą',
        'cart_promo_already': 'Nuolaidos kodas jau pritaikytas.',
        'cart_promo_unavailable': 'Šioms prekėms nuolaidos kodai negalioja.',
        'cart_promo_prompt': 'Įrašykite krepšelio nuolaidos kodą:',
        'cart_promo_removed': 'Nuolaidos kodas pašalintas iš krepšelio.',
        'cart_promo_not_applied': 'Krepšelyje nėra nuolaidos kodo, kurį būtų galima pašalinti.',
        'cart_promo_invalid': '❌ Neteisingas arba pasibaigęs nuolaidos kodas krepšeliui.',
        'cart_promo_applied': '✅ Nuolaidos kodas {code} pritaikytas ({percent}%).',
        'cart_promo_blocked': '⚠️ Nuolaidos kodas negalioja: {items}.',
        'cart_promo_blocked_reason_category': 'kategorija uždrausta',
        'cart_promo_blocked_reason_assignment': 'nepriskirta',
        'cart_promo_no_applicable_items': '❌ Šio nuolaidos kodo negalima pritaikyti jokiai krepšelio prekei.',
        'cart_insufficient_balance': '❌ Nepakanka lėšų. Trūksta {missing}€.',
        'cart_lottery_awarded': '🎟️ Gavote {count} loterijos bilietus.',
        'cart_checkout_success': '✅ Įsigyta prekių: {count} už {total}€. Likutis: {balance}€.',
        'cart_checkout_success_balance': '✅ Įsigyta prekių: {count} už {total}€. Panaudota balanso: {balance_used}€. Likutis: {balance}€.',
        'cart_checkout_failed': '❌ Nepavyko atlikti apmokėjimo. Bandykite vėliau.',
        'cart_checkout_partial': '⚠️ Nepavyko įsigyti: {items}.',
        'cart_delivery_caption': '✅ {item}\n💰 Likutis: {balance}€\n📦 Pirkinių: {purchases}',
        'cart_delivery_text': '✅ {item}\n💰 Likutis: {balance}€\n📦 Pirkinių: {purchases}\n\n{value}',
        'cart_notify_restock': '🔔 Priminti man',
        'cart_out_of_stock_removed': '⚠️ {item} pašalinta, nes atsargos pasibaigė.',
        'cart_quantity_adjusted': 'ℹ️ {item} kiekis pakeistas į {quantity} dėl ribotų atsargų.',
        'games': '🎮 Žaidimai',
        'blackjack': '🃏 Blackjack',
        'coinflip': '🪙 Monetos metimas',
        'coinflip_disabled': '🪙 Monetos metimas laikinai nepasiekiamas.',
        'achievements': '🏆 Pasiekimai',
        'quests': '🧩 Asmeniniai uždaviniai',
        'quests_placeholder': '🔧 Uždaviniai greitai atsiras.',
        'find_game': '🔍 Rasti žaidimą',
        'create_game': '➕ Sukurti žaidimą',
        'play_bot': '🤖 Žaisti su botu',
        'choose_game': 'Pasirinkite žaidimą',
        'choose_side': 'Pasirinkite pusę:',
        'enter_bet': 'Įveskite statymo sumą:',
        'heads': 'Herbas',
        'tails': 'Skaičius',
        'not_enough_balance': '❌ Nepakanka lėšų',
        'win': 'Laimėjote {amount}€!',
        'lose': 'Pralaimėjote {amount}€.',
        'back': '🔙 Atgal',
        'create': '✅ Sukurti',
        'join': '✅ Prisijungti',
        'waiting_opponent': '⏳ Laukiama priešininko...',
        'no_games': '❌ Nėra žaidimų',
        'join_confirm': 'Žaisti prieš {user} už {bet}€ kaip {side}?',
        'create_confirm': 'Sukurti žaidimą už {bet}€ kaip {side}?',
        'game_cancelled': 'Žaidimas atšauktas. Statymas grąžintas.',
        'select_room': 'Pasirinkite žaidimą prisijungti:',
        'achievement_start': 'Parašykite /start botui',
        'achievement_first_purchase': 'Atlikite pirmą pirkimą',
        'achievement_first_topup': 'Papildykite balansą',
        'achievement_first_blackjack': 'Sužaiskite Blackjack',
        'achievement_first_coinflip': 'Sužaiskite monetą',
        'achievement_gift_sent': 'Išsiųskite dovaną',
        'achievement_first_referral': 'Pakvieskite draugą',
        'achievement_five_purchases': 'Nupirkite 5 prekes',
        'achievement_streak_three': '3 dienų pirkimų serija',
        'achievement_ten_referrals': 'Pakvieskite 10 draugų',
        'achievement_unlocked': '🏆 Pasiekimas atrakintas: {name}',
        'show_unlocked': 'Rodyti pasiektus',
        'show_locked': 'Rodyti nepasiektus',
        'level_up': '🎉 Sveikiname! Pasiekėte {level}.',


        'achievement_unlocked': '🏆 Pasiekimas atrakintas: {name}',




    },
}

def t(lang: str, key: str, **kwargs) -> str:
    lang_data = LANGUAGES.get(lang, LANGUAGES['en'])
    template = lang_data.get(key, '')
    return _apply_ui_emojis(template.format(**kwargs))
